### ISSUE TITLE
The GetPresignedObjectUrl() function has an error and does not return the correct value.

### ISSUE THREAD

**Issue by bboy-hui** [minio/minio-cpp#131] opened 2024-04-07 06:06 UTC
The expected signature generation is incomplete.

**Comment by balamurugana** [comment] 2024-04-07 11:45
Duplicate of https://github.com/minio/minio-cpp/issues/110

**Comment by bboy-hui** [comment] 2024-04-07 12:56
You can use an example to test it; the returned URL is incomplete. The function utils::Multimap PresignV4(http::Method method, the std::string& host, the std::string& uri, the std::string& region, utils::Multimap query_params, the std::string& access_key, the std::string& secret_key, the utils::UtcTime& date, unsigned int expires) is erroneous.

**Comment by ijoseph** [comment] 2024-04-13 02:27
Found the bug. `query_params` needs to be passed by reference into `PreSignV4`, otherwise the query params are lost with the stack frame when it returns. 

```diff 
diff --git a/include/miniocpp/signer.h b/include/miniocpp/signer.h
index b8c912b..670a93d 100644
--- a/include/miniocpp/signer.h
+++ b/include/miniocpp/signer.h
@@ -69,7 +69,7 @@ utils::Multimap SignV4STS(http::Method method, const std::string& uri,
                           const utils::UtcTime& date);
 utils::Multimap PresignV4(http::Method method, const std::string& host,
                           const std::string& uri, const std::string& region,
-                          utils::Multimap query_params,
+                          utils::Multimap& query_params,
                           const std::string& access_key,
                           const std::string& secret_key,
                           const utils::UtcTime& date, unsigned int expires);
diff --git a/src/signer.cc b/src/signer.cc
index c3ffb59..067f6b0 100644
--- a/src/signer.cc
+++ b/src/signer.cc
@@ -165,7 +165,7 @@ utils::Multimap SignV4STS(http::Method method, const std::string& uri,
 
 utils::Multimap PresignV4(http::Method method, const std::string& host,
                           const std::string& uri, const std::string& region,
-                          utils::Multimap query_params,
+                          utils::Multimap& query_params,
                           const std::string& access_key,
                           const std::string& secret_key,
                           const utils::UtcTime& date, unsigned int expires) {
```

**Comment by ijoseph** [comment] 2024-04-13 02:32
Before the above fix, we just get a bare URL with no query params whatsoever.

**Closed** 2024-05-15 06:46 UTC
