### ISSUE TITLE
The file obtained by DownloadObject is damaged

### ISSUE THREAD

**Issue by tilongzs** [minio/minio-cpp#182] opened 2024-12-23 11:10 UTC
The same image object, after obtaining binary data through `GetObject `and saving it locally, is not consistent with the file downloaded directly through `DownloadObject`.
The file size obtained by `DownloadObject `is slightly larger and incorrect.

```
int main() {
	// Create S3 base URL.
	BaseUrl base_url("192.168.20.50:9000", false);

	// Create credential provider.
	minio::creds::StaticProvider provider(
		"xxxx", "xxxxxxxx");

	// Create S3 client.
	Client client(base_url, &provider);

	string bucketName = "ootd";
	string objectName = "_ootd_uid_WxKV5mC71paH-9sOECJpGGiI1J";
	int objectSize = 0;
	{
		StatObjectArgs args;
		args.bucket = bucketName;
		args.object = objectName;

		StatObjectResponse resp = client.StatObject(args);
		if (resp) 
		{
			objectSize = resp.size;
		}
		else
		{
			std::cout << "unable to StatObject " << resp.Error().String() << std::endl;
			return -1;
		}
	}


	{
		char* buffer = new char[objectSize];
		memset(buffer, 0, objectSize);

		int recvSize = 0;
		GetObjectArgs args;
		args.bucket = bucketName;
		args.object = objectName;
		args.datafunc = [&](DataFunctionArgs dataArgs) -> bool {
			int dataSize = dataArgs.datachunk.size();

			memcpy(buffer + recvSize, dataArgs.datachunk.data(), dataSize);
			recvSize += dataSize;
			std::cout << "recv size:" << recvSize << endl;
			return true;
		};

		GetObjectResponse resp = client.GetObject(args);
		if (resp) 
		{
			std::ofstream file("T:/GetObject.webp", std::ios::binary);
			if (!file.is_open()) {
				return 0;
			}

			file.write(buffer, objectSize);

			file.close();

			cout << "Get object success" << endl;
		}
		else 
		{
			std::cout << "unable to get object; " << resp.Error().String() << std::endl;
			return -1;
		}

		delete[] buffer;
	}

	{
		DownloadObjectArgs args;
		args.bucket = bucketName;
		args.object = objectName;
		args.filename = "T:/DownloadObject.webp";

		DownloadObjectResponse resp = client.DownloadObject(args);
		if (!resp)
		{
			cout << "unable to download object; " << resp.Error().String() << endl;
			return EXIT_FAILURE;
		}

		cout << "DownloadObject object success" << endl;
	}

	return EXIT_SUCCESS;
}
```

**Comment by balamurugana** [comment] 2024-12-23 11:32
Duplicate of https://github.com/minio/minio-cpp/issues/145

**Closed by balamurugana** 2024-12-23 11:32 UTC
