### ISSUE TITLE
vcpkg minio-cpp package v0.2.0 broken. Opening a connection gives "RequestTimeTooSkewed: The difference between the request time and the server's time is too large."

### ISSUE THREAD

**Issue by javimm77** [minio/minio-cpp#150] opened 2024-06-26 14:49 UTC
I'm trying to use minio-cpp through an vcpkg installation. The package version vcpkg downloads corresponds to tag v0.2.0. Trying the most simple example, for instance, "BucketExists.cc", gives the following error:
"unable to do bucket existence check; RequestTimeTooSkewed: The difference between the request time and the server's time is too large."
This error appears in three different machines. Trying the same connection with a Python interface, I can reach the bucket without problem in all three machines.
I managed to get this to work by cloning the latest code from github and compiling it. With the latest code, I can connect without any problem.
Trying to prove my point, I switched my local minio-cpp repo to tag v0.2.0 and recompiled and the error appeared again, so the problem should be in the v0.2.0 tag.
Is it possible to create a new tag with the fixes from "main" and upload the new working package to the official vcpkg repos?.
I'm not familiar with vcpkg, and I don't know if a workaround is possible.
Thanks.

**Comment by HJLebbink** [comment] 2024-06-26 19:32
Hi Petr, @kobalicek and Piotr, @piotr-topnotch, have you seen such skews before? I know there was a lot of fiddling with wall-time handing by several people. Just wonderering if you guys seen it; that could help to reproduce it.

**Comment by javimm77** [comment] 2024-06-26 20:29
Just to clarify things a bit. the current "main" branch works (it connects without skew errors), but tag v0.2.0 doesn't. I guess the fix is already in the "main" branch.

**Comment by balamurugana** [comment] 2024-06-27 01:00
Duplicate of https://github.com/minio/minio-cpp/issues/132

**Closed by balamurugana** 2024-06-27 01:00 UTC

**Comment by javimm77** [comment] 2024-06-27 06:35
The issue has been closed, but the issue I reported (vcpkg minio-cpp package is broken in the official vcpkg repos as it is based on v.0.2.0) is still present.
Are there any plans to update the vcpkg package with the fixes in main?.
Thank you.

**Comment by balamurugana** [comment] 2024-06-27 07:17
Stay tuned for next release

**Comment by aliddell** [comment] 2024-07-02 15:23
I don't think this issue should be closed until there's either a release or a plan for one. I lost several hours trying to figure out what's wrong with my code, when it turns out this critical error is hidden behind a closed issue.

**Comment by kobalicek** [comment] 2024-07-03 09:10
I agree - some projects have "fixed-not-released" tag, would be appropriate (without closing)
